/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CbToast {
        "Toast": (toast: any) => Promise<void>;
    }
    interface CbToastcontent {
        "setParams": (toast: any) => Promise<void>;
    }
}
declare global {
    interface HTMLCbToastElement extends Components.CbToast, HTMLStencilElement {
    }
    var HTMLCbToastElement: {
        prototype: HTMLCbToastElement;
        new (): HTMLCbToastElement;
    };
    interface HTMLCbToastcontentElement extends Components.CbToastcontent, HTMLStencilElement {
    }
    var HTMLCbToastcontentElement: {
        prototype: HTMLCbToastcontentElement;
        new (): HTMLCbToastcontentElement;
    };
    interface HTMLElementTagNameMap {
        "cb-toast": HTMLCbToastElement;
        "cb-toastcontent": HTMLCbToastcontentElement;
    }
}
declare namespace LocalJSX {
    interface CbToast {
    }
    interface CbToastcontent {
    }
    interface IntrinsicElements {
        "cb-toast": CbToast;
        "cb-toastcontent": CbToastcontent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cb-toast": LocalJSX.CbToast & JSXBase.HTMLAttributes<HTMLCbToastElement>;
            "cb-toastcontent": LocalJSX.CbToastcontent & JSXBase.HTMLAttributes<HTMLCbToastcontentElement>;
        }
    }
}
